### ISSUE TITLE
Clarification on CI/CD

### ISSUE THREAD

**Issue by NBaron** [posva/nuxt--vuefire-example-blaze-plan#2]
Hello @posva,

Thank you for this repo. It is a great example for anyone stitching Nuxt and Firebase.

Regarding the CI/CD, there is a need for clarification regarding the appropriate command to use.

It is stated in the README, that using SSR with a Firebase Blaze plan, one should use `pnpm run build`.
https://github.com/posva/nuxt--vuefire-example-blaze-plan#building-for-production

Whereas, in the file `firebase-hosting-pull-request.yml`, the build site task use `pnpm run generate`:
```
      - name: Build site
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NUXT_VUEFIRE_EXAMPLE_SPARK }}
        run: pnpm run generate
```
https://github.com/posva/nuxt--vuefire-example-blaze-plan/blob/e51fbd3a963c928b8d8ba74889d8052bb4c51537/.github/workflows/firebase-hosting-pull-request.yml

I would suppose that `build` is the right way to go.
**Can you clarify?**

I have created this PR https://github.com/posva/nuxt--vuefire-example-blaze-plan/pull/3 in advance.

Thank you in advance.
